$ANSIBLE_VAULT;1.1;AES256
36366435383035353134633765366661633064643239373631393734373066646165663239393864
3061333662313561363332316433343635386363343539650a666366643066653036376164636462
66613039373135323738623237326638383234333237643134353032633466643166303365653433
6638343935356538310a373861653131383037333166393638346261363765363034663566363562
30666634356630653361386233633636623632623734346561313934333266663932333361633330
33323765613664646136396234623932656636343737333838353062306261303561303465613335
35386263326663633737346563663038656164333733383235393839356633376133653834313134
38643363373763393535383961323038386338623462643432613566633830653864636133323230
37633365636636656335653733343566333939363735616130356263386330393435646461333064
31303331633137303866343238646537383135396636303335386466323239623565346563363439
62333463666663613365343131386665326263373831303239643731646132363535356663316432
34363638326566643939313733306430633636306664346638653531363237636337376536323662
37336262386232623532316162653231366161346430333336316164613962396639356539626562
6337646339613961623466643765383432336639323137653334
